version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:06"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # 允许的更新类型
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"