# 死亡笔记黑名单配置示例
# 该配置文件在构建时被读取，黑名单数据将被编译到最终产物中
# 这样既保证了性能（编译时内嵌），又便于开发环境中管理配置
# 复制此文件为 blacklist_config.toml 并根据需要修改配置
# 本地真实配置建议加入 .gitignore 防止泄露敏感数据

[coolapk]
# 酷安平台黑名单用户
users = [
    "1234567",  # 被琉克记录的酷安用户1
    "9999999",  # 被琉克记录的酷安用户2
    "2468135",  # 被琉克记录的酷安用户3
    "9876543",  # 新增的酷安用户4（演示配置更新）
]

[qq]
# QQ平台黑名单用户
users = [
    "123456789",  # 被琉克记录的QQ用户1
    "987654321",  # 被琉克记录的QQ用户2
    "555555555",  # 被琉克记录的QQ用户3
    "111111111",  # 被琉克记录的QQ用户4
]

[telegram]
# Telegram平台黑名单用户
users = [
    "100000000",  # 被琉克记录的Telegram用户1
    "200000000",  # 被琉克记录的Telegram用户2
    "300000000",  # 被琉克记录的Telegram用户3
]

# 配置元信息
[meta]
version = "1.0"
description = "死亡笔记黑名单配置文件"
last_updated = "2025-09-14"
