[package]
name = "android_rust_project"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
quick-xml = "0.36"
regex = "1.11"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.7"
