[target.aarch64-linux-android]
linker = "D:/android-ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang.cmd"
ar = "D:/android-ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android-ar.exe"

[env]
NDK_HOME = { value = "D:/android-ndk", relative = false }